using System.Globalization;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Shapes;using DXFExplorer;using DXFHelp;using Microsoft.Win32;
namespace DXFDrawer;
public partial class MainWindow:Window
{
 readonly HistoryManager history=new();string? file;bool syncingSelection;
 sealed record ObjectListItem(EditorEntity Entity,bool HasError){public override string ToString()=>$"{(HasError?"⚠ ":"   ")}#{Entity.Id,-3} {Type(Entity),-7} {Entity.Layer.Trim('-')}";static string Type(EditorEntity e)=>e switch{EditorLine=>"LINE",EditorArc=>"ARC",EditorCircle=>"CIRCLE",_=>"ENTITY"};}
 public MainWindow(){InitializeComponent();Canvas.Changed+=(_,_)=>Refresh(true);Canvas.SelectionChanged+=(_,_)=>SyncSelectionFromCanvas();Canvas.SectionChanged+=(_,change)=>{if(change.Axis==SectionAxis.X)XSimulation.SetDocument(Canvas.Document,change.Position,true);else YSimulation.SetDocument(Canvas.Document,change.Position,true);UpdateStatus();};Canvas.ToolChanged+=(_,_)=>{UpdateToolButtons();Refresh(false);};Canvas.ValidationRejected+=(_,message)=>{Status.Text=message;MessageBox.Show(message,"Geometry Validation",MessageBoxButton.OK,MessageBoxImage.Warning);};Canvas.BeforeChange+=(_,_)=>history.Checkpoint(Canvas.Document);Canvas.CoordinateChanged+=(_,p)=>Coordinates.Text=$"X: {p.X:0.000}   Y: {p.Y:0.000}";PreviewKeyDown+=(_,e)=>{if(e.Key==System.Windows.Input.Key.F1){HelpLauncher.Open(this,"DXFDrawer_help.html");e.Handled=true;}else if(e.Key==System.Windows.Input.Key.Delete){Canvas.DeleteSelected();e.Handled=true;}else if(e.Key==System.Windows.Input.Key.Escape){Canvas.CancelInteraction();e.Handled=true;}};Loaded+=(_,_)=>{Canvas.Fit();Canvas.EnsureSections();UpdateSimulations(true);UpdateToolButtons();};}
 void Refresh(bool drawingChanged=false){Canvas.EnsureSections();RefreshObjectList();BuildProperties();if(drawingChanged)UpdateSimulations(true);ContourInfo.Text=$"Entity: {Canvas.Document.Entities.Count}\nClosed contour: {ContourAnalyzer.Closed(Canvas.Document).Count}";UpdateStatus();}
 void UpdateStatus(){var selected=Canvas.Selected is null?"선택 없음":$"선택 #{Canvas.Selected.Id}";var layer=DesignerCanvas.GetLayerForTool(Canvas.Tool)??"-";Status.Text=$"Layer {layer} | {Canvas.Tool} | {selected} | X Section {Canvas.XSectionPosition:0.###} | Y Section {Canvas.YSectionPosition:0.###}";}
 void UpdateSimulations(bool reset){XSimulation.SetDocument(Canvas.Document,Canvas.XSectionPosition,reset);YSimulation.SetDocument(Canvas.Document,Canvas.YSectionPosition,reset);}
 void RefreshObjectList(){var selectedId=Canvas.Selected?.Id;var errors=DrawingValidation.Validate(Canvas.Document).Select(x=>x.EntityId).ToHashSet();syncingSelection=true;ObjectList.ItemsSource=Canvas.Document.Entities.Select(x=>new ObjectListItem(x,errors.Contains(x.Id))).ToList();ObjectList.SelectedItem=ObjectList.Items.Cast<ObjectListItem>().FirstOrDefault(x=>x.Entity.Id==selectedId);if(ObjectList.SelectedItem is not null)ObjectList.ScrollIntoView(ObjectList.SelectedItem);syncingSelection=false;}
 void SyncSelectionFromCanvas(){Refresh(false);}
 void ObjectList_SelectionChanged(object s,SelectionChangedEventArgs e){if(syncingSelection)return;Canvas.SelectEntity((ObjectList.SelectedItem as ObjectListItem)?.Entity.Id);}
 void ObjectList_MouseDoubleClick(object s,System.Windows.Input.MouseButtonEventArgs e){if(ObjectList.SelectedItem is ObjectListItem item){Canvas.SelectEntity(item.Entity.Id);Canvas.LocateSelected();}}
 void New_Click(object s,RoutedEventArgs e){history.Checkpoint(Canvas.Document);Canvas.Document=new();file=null;}
 void Open_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="DXF (*.dxf)|*.dxf"};if(d.ShowDialog()!=true)return;try{history.Checkpoint(Canvas.Document);Canvas.Document=DrawingDocument.Load(d.FileName);file=d.FileName;}catch(Exception ex){MessageBox.Show(ex.Message,"DXF 열기",MessageBoxButton.OK,MessageBoxImage.Error);}}
 void Save_Click(object s,RoutedEventArgs e){var issues=DrawingValidation.Validate(Canvas.Document).Where(x=>x.Severity==ValidationSeverity.Error).ToList();if(issues.Count>0){Canvas.SelectEntity(issues[0].EntityId);MessageBox.Show(string.Join(Environment.NewLine,issues.Select(x=>x.DisplayText)),"Validation 오류",MessageBoxButton.OK,MessageBoxImage.Warning);return;}var d=new SaveFileDialog{Filter="DXF (*.dxf)|*.dxf",FileName=file is null?"drawing.dxf":System.IO.Path.GetFileName(file)};if(d.ShowDialog()!=true)return;try{DxfWriter.Save(Canvas.Document,d.FileName);file=d.FileName;Status.Text=$"저장됨: {d.FileName}";}catch(DrawingValidationException ex){if(ex.Issues.Count>0)Canvas.SelectEntity(ex.Issues[0].EntityId);MessageBox.Show(ex.Message,"Validation 오류",MessageBoxButton.OK,MessageBoxImage.Warning);}catch(Exception ex){MessageBox.Show(ex.Message,"DXF 저장",MessageBoxButton.OK,MessageBoxImage.Error);}}
 void Tool_Click(object s,RoutedEventArgs e){if(s is Button b&&Enum.TryParse<DrawTool>(b.Tag?.ToString(),out var tool))Canvas.SetTool(tool);}
 void UpdateToolButtons(){var map=new Dictionary<Button,DrawTool>{{SelectTool,DrawTool.Select},{LineTool,DrawTool.Line},{ArcTool,DrawTool.Arc},{CircleTool,DrawTool.Circle},{VLineTool,DrawTool.VLine},{V1LineTool,DrawTool.V1Line}};foreach(var pair in map){var active=Canvas.Tool==pair.Value;pair.Key.Background=active?new SolidColorBrush(Color.FromRgb(37,99,235)):SystemColors.ControlBrush;pair.Key.Foreground=active?Brushes.White:SystemColors.ControlTextBrush;pair.Key.FontWeight=active?FontWeights.Bold:FontWeights.Normal;}}
 void LayerVisibility_Click(object s,RoutedEventArgs e){Canvas.SetLayerVisible("-L-",ShowL.IsChecked==true);Canvas.SetLayerVisible("-V-",ShowV.IsChecked==true);Canvas.SetLayerVisible("-V1-",ShowV1.IsChecked==true);}
 void Settings_Click(object s,RoutedEventArgs e){Canvas.GridVisible=ShowGrid.IsChecked==true;Canvas.GridSnap=SnapGrid.IsChecked==true;Canvas.EndpointSnap=SnapEnd.IsChecked==true;if(double.TryParse(GridSize.Text,out var n)&&n>0)Canvas.GridSize=n;Canvas.InvalidateVisual();Refresh();}
 void Delete_Click(object s,RoutedEventArgs e)=>Canvas.DeleteSelected();void Fit_Click(object s,RoutedEventArgs e)=>Canvas.Fit();
 void Help_Click(object s,RoutedEventArgs e)=>HelpLauncher.Open(this,"DXFDrawer_help.html");
 void Undo_Click(object s,RoutedEventArgs e){var d=history.Undo(Canvas.Document);if(d is not null)Canvas.Document=d;}void Redo_Click(object s,RoutedEventArgs e){var d=history.Redo(Canvas.Document);if(d is not null)Canvas.Document=d;}
 void BuildProperties(){Properties.Children.Clear();var e=Canvas.Selected;if(e is null){Properties.Children.Add(new TextBlock{Text="도형을 선택하면 좌표와 형상 속성을 편집할 수 있습니다.",TextWrapping=TextWrapping.Wrap});return;}Add("Entity",$"{e.Id} / {e.GetType().Name}",false,null);Add("Layer",e.Layer,true,ReplaceLayer);switch(e){case EditorLine l:AddNumber("Start X",l.Start.X,v=>l with{Start=l.Start with{X=v}});AddNumber("Start Y",l.Start.Y,v=>l with{Start=l.Start with{Y=v}});AddNumber("End X",l.End.X,v=>l with{End=l.End with{X=v}});AddNumber("End Y",l.End.Y,v=>l with{End=l.End with{Y=v}});Add("ΔX",l.Dx.ToString("0.###"),false,null);Add("ΔY",l.Dy.ToString("0.###"),false,null);AddNumber("Length",l.Length,v=>ResizeLine(l,v,l.AngleRadians));AddNumber("Angle °",l.AngleDegrees,v=>ResizeLine(l,l.Length,GeometryMath.DegreesToRadians(v)));Add("Gradient",l.Gradient?.ToString("0.######")??"Vertical",false,null);Add("Direction",l.Horizontal?"Horizontal":l.Vertical?"Vertical":"Diagonal",false,null);break;case EditorCircle c:AddNumber("Center X",c.Center.X,v=>c with{Center=c.Center with{X=v}});AddNumber("Center Y",c.Center.Y,v=>c with{Center=c.Center with{Y=v}});AddNumber("Radius",c.Radius,v=>c with{Radius=v});break;case EditorArc a:AddNumber("Center X",a.Center.X,v=>a with{Center=a.Center with{X=v}});AddNumber("Center Y",a.Center.Y,v=>a with{Center=a.Center with{Y=v}});AddNumber("Radius",a.Radius,v=>a with{Radius=v});AddNumber("Start Angle",a.StartAngle,v=>a with{StartAngle=v});AddNumber("End Angle",a.EndAngle,v=>a with{EndAngle=v});Add("Sweep",a.SweepAngle.ToString("0.###"),false,null);break;}}
 EditorLine ResizeLine(EditorLine l,double len,double angle)=>l with{End=new(l.Start.X+len*Math.Cos(angle),l.Start.Y+len*Math.Sin(angle))};
 void ReplaceLayer(string value){var layer=value.Trim() switch{"L" or "-L-"=>"-L-","V" or "-V-"=>"-V-","V1" or "-V1-"=>"-V1-",_=>value};var e=Canvas.Selected!;EditorEntity n=e switch{EditorLine x=>x with{EntityLayer=layer},EditorCircle x=>x with{EntityLayer=layer},EditorArc x=>x with{EntityLayer=layer},_=>e};if(layer!="-L-"&&n is not EditorLine){MessageBox.Show("V/V1에는 직선만 허용됩니다.");return;}Canvas.ReplaceSelected(n);}
 void AddNumber(string name,double value,Func<double,EditorEntity> change)=>Add(name,value.ToString("0.######",CultureInfo.InvariantCulture),true,s=>{if(double.TryParse(s,NumberStyles.Float,CultureInfo.InvariantCulture,out var v))Canvas.ReplaceSelected(change(v));});
 void Add(string name,string value,bool edit,Action<string>? apply){var row=new Grid{Margin=new(0,2,0,2)};row.ColumnDefinitions.Add(new(){Width=new GridLength(100)});row.ColumnDefinitions.Add(new());row.Children.Add(new TextBlock{Text=name,VerticalAlignment=VerticalAlignment.Center});var box=new TextBox{Text=value,IsReadOnly=!edit};Grid.SetColumn(box,1);row.Children.Add(box);if(edit)box.KeyDown+=(_,k)=>{if(k.Key==System.Windows.Input.Key.Enter)apply?.Invoke(box.Text);};Properties.Children.Add(row);}
 void XReset_Click(object s,RoutedEventArgs e)=>XSimulation.Reset();void YReset_Click(object s,RoutedEventArgs e)=>YSimulation.Reset();
}
