using System.Windows;using System.Windows.Input;using System.Windows.Media;using DXFExplorer;
namespace DXFDrawer;
public sealed class SideBendingSimulationControl:FrameworkElement
{
 DrawingDocument? document;SectionProjection? projection;BendSimulation? simulation;readonly List<int> folded=[];readonly Dictionary<int,Point> handles=[];
 public SectionAxis Axis{get;set;}public double SectionPosition{get;private set;}public event EventHandler<int>? BendPointSelected;
 public SideBendingSimulationControl(){Background=Brushes.White;ClipToBounds=true;}public Brush Background{get;set;}
 public void SetDocument(DrawingDocument value,double position,bool reset=true){document=value;SectionPosition=position;if(reset)folded.Clear();Rebuild();}
 public void Reset(){folded.Clear();Rebuild();}
 void Rebuild(){projection=null;simulation=null;if(document is null||document.Entities.Count==0){InvalidateVisual();return;}try{projection=SectionAnalyzer.Analyze(document,Axis,SectionPosition);simulation=new BendSimulation(projection.Model);folded.RemoveAll(id=>projection.Model.Hinges.All(h=>h.EntityId!=id));foreach(var id in folded)simulation.Bend(id);}catch{}InvalidateVisual();}
 protected override void OnRender(DrawingContext dc){dc.DrawRectangle(Background,null,new Rect(RenderSize));handles.Clear();if(projection is null||simulation is null||simulation.Points.Count<2){Text(dc,"No section geometry",new(12,12),Brushes.Gray);return;}var points=simulation.Points;var min=projection.Model.MinY;var max=projection.Model.MaxY;var span=Math.Max(1,max-min);var maxOffset=Math.Max(1,points.Max(p=>Math.Abs(p.Offset)));var alongSpace=Axis==SectionAxis.X?ActualWidth-36:ActualHeight-52;var offsetSpace=Axis==SectionAxis.X?ActualHeight-52:ActualWidth-36;var scale=Math.Min(Math.Max(.01,alongSpace/span),Math.Max(.01,offsetSpace/(maxOffset*2)));Point S(SectionPoint p)=>Axis==SectionAxis.X?new(18+(p.AlongSection-min)*scale,ActualHeight/2-p.Offset*scale):new(ActualWidth/2+p.Offset*scale,ActualHeight-18-(p.AlongSection-min)*scale);var pen=new Pen(Brushes.SlateBlue,3);for(var i=1;i<points.Count;i++)dc.DrawLine(pen,S(points[i-1]),S(points[i]));foreach(var h in projection.Model.Hinges){var index=projection.Model.Hinges.ToList().FindIndex(x=>x.EntityId==h.EntityId)+1;if(index<1||index>=points.Count)continue;var p=S(points[index]);handles[h.EntityId]=p;var brush=h.Layer.Trim('-').Equals("V1",StringComparison.OrdinalIgnoreCase)?Brushes.DodgerBlue:Brushes.Red;dc.DrawEllipse(folded.Contains(h.EntityId)?brush:Brushes.White,new Pen(brush,2),p,7,7);}Text(dc,$"{Axis} Section = {SectionPosition:0.###}",new(10,8),Brushes.DimGray);if(handles.Count==0)Text(dc,"No bending points on this section",new(10,ActualHeight-28),Brushes.Gray);}
 protected override void OnMouseLeftButtonDown(MouseButtonEventArgs e){var p=e.GetPosition(this);var hit=handles.OrderBy(x=>(x.Value-p).Length).FirstOrDefault();if(hit.Key==0||(hit.Value-p).Length>12)return;if(folded.Contains(hit.Key))folded.Remove(hit.Key);else folded.Add(hit.Key);BendPointSelected?.Invoke(this,hit.Key);Rebuild();}
 static void Text(DrawingContext dc,string value,Point p,Brush brush)=>dc.DrawText(new(value,System.Globalization.CultureInfo.CurrentCulture,FlowDirection.LeftToRight,new Typeface("Segoe UI"),12,brush,1),p);
}
