<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Reference Include="DXFDrawer"><HintPath>..\DXFDrawer\bin\Debug\net10.0-windows\DXFDrawer.dll</HintPath></Reference><Reference Include="DXFViewer"><HintPath>..\DXFExplorer\bin\Debug\net10.0-windows\DXFViewer.dll</HintPath></Reference></ItemGroup></Project>
