using DXFDrawer;using DXFExplorer;using System.IO;
LineMath();Angles();ToolLayers();ArcDirectionMath();Contours();Validation();OverlapRules();Sections();RoundTrip();Console.WriteLine("DXFDrawer geometry tests passed.");
static void LineMath(){var l=new EditorLine(1,"-L-",new(0,0),new(3,4));Eq(5,l.Length);Eq(4d/3,l.Gradient!.Value);if(l.Horizontal||l.Vertical)Fail("direction");var v=new EditorLine(2,"-V-",new(2,0),new(2,9));if(!v.Vertical||v.Gradient is not null)Fail("vertical");}
static void Angles(){Eq(Math.PI,GeometryMath.DegreesToRadians(180));Eq(200,GeometryMath.RadiansToGradians(Math.PI));var l=new EditorLine(1,"-L-",new(0,0),new(-1,1));Eq(135,l.AngleDegrees);}
static void ToolLayers(){if(DesignerCanvas.GetLayerForTool(DrawTool.Line)!="-L-"||DesignerCanvas.GetLayerForTool(DrawTool.Arc)!="-L-"||DesignerCanvas.GetLayerForTool(DrawTool.Circle)!="-L-"||DesignerCanvas.GetLayerForTool(DrawTool.VLine)!="-V-"||DesignerCanvas.GetLayerForTool(DrawTool.V1Line)!="-V1-"||DesignerCanvas.GetLayerForTool(DrawTool.Select) is not null)Fail("tool layer mapping");}
static void ArcDirectionMath(){var original=new EditorArc(1,"-L-",new(170,40),20,0,180,ArcDirection.Clockwise);var edited=original.WithStartAngle(90);Eq(170,edited.Center.X);Eq(40,edited.Center.Y);Eq(20,edited.Radius);Eq(180,edited.EndAngle);Eq(90,edited.StartAngle);Eq(90,edited.SweepAngle);Eq(170,edited.StartPoint.X);Eq(60,edited.StartPoint.Y);Eq(150,edited.EndPoint.X);Eq(40,edited.EndPoint.Y);Eq(20,Distance(edited.Center,edited.StartPoint));Eq(20,Distance(edited.Center,edited.EndPoint));var endEdited=original.WithEndAngle(90);Eq(0,endEdited.StartAngle);Eq(90,endEdited.SweepAngle);Eq(135,new EditorArc(2,"-L-",new(0,0),10,45,180).SweepAngle);Eq(180,new EditorArc(3,"-L-",new(0,0),10,90,270).SweepAngle);Eq(20,new EditorArc(4,"-L-",new(0,0),10,350,10).SweepAngle);var path=Path.Combine(Path.GetTempPath(),$"arc-edit-{Guid.NewGuid():N}.dxf");try{var d=new DrawingDocument();d.Entities.Add(edited);DxfWriter.Save(d,path);var loaded=DrawingDocument.Load(path).Entities.OfType<EditorArc>().Single();Eq(170,loaded.Center.X);Eq(40,loaded.Center.Y);Eq(20,loaded.Radius);Eq(90,loaded.StartAngle);Eq(180,loaded.EndAngle);Eq(90,loaded.SweepAngle);}finally{if(File.Exists(path))File.Delete(path);}}
static void Contours(){var d=new DrawingDocument();d.Entities.AddRange([new EditorLine(1,"-L-",new(0,0),new(10,0)),new EditorLine(2,"-L-",new(10,0),new(10,10)),new EditorLine(3,"-L-",new(10,10),new(0,10)),new EditorLine(4,"-L-",new(0,10),new(0,0)),new EditorCircle(5,"-L-",new(5,5),2)]);if(ContourAnalyzer.Closed(d).Count!=2)Fail("contours");}
static void Validation(){var d=new DrawingDocument();d.Entities.Add(new EditorLine(8,"-L-",new(100,100),new(100,100)));var issue=DrawingValidation.Validate(d).Single();if(issue.EntityId!=8||issue.EntityType!="LINE"||issue.Layer!="-L-"||issue.Code!="ZERO_LENGTH_LINE")Fail("structured zero-length validation");d.Entities[0]=new EditorLine(8,"-L-",new(100,100),new(150,100));if(DrawingValidation.Validate(d).Count!=0)Fail("fixed zero-length validation");d.Entities.Add(new EditorLine(9,"-V-",new(0,0),new(1,1)));if(DrawingValidation.Validate(d).Single().EntityId!=9)Fail("V validation");}
static void OverlapRules(){var cut=new EditorLine(1,"-L-",new(0,0),new(100,0));var full=new EditorLine(2,"-V-",new(0,0),new(100,0));var inside=new EditorLine(3,"-V-",new(20,0),new(80,0));var partial=new EditorLine(4,"-V1-",new(50,0),new(150,0));var cross=new EditorLine(5,"-V-",new(50,-50),new(50,50));var touch=new EditorLine(6,"-V-",new(100,0),new(150,0));if(GeometryRules.CollinearOverlapLength(cut,full)<99||GeometryRules.CollinearOverlapLength(cut,inside)<59||GeometryRules.CollinearOverlapLength(cut,partial)<49)Fail("overlap rejection");if(GeometryRules.CollinearOverlapLength(cut,cross)>0||GeometryRules.CollinearOverlapLength(cut,touch)>GeometryMath.Epsilon)Fail("intersection/touch allowed");var d=new DrawingDocument();d.Entities.AddRange([cut,inside]);if(DrawingValidation.Validate(d).Single().Code!="CUT_BEND_OVERLAP")Fail("save overlap validation");}
static void Sections(){var d=new DrawingDocument();d.Entities.AddRange([new EditorLine(1,"-L-",new(0,0),new(100,0)),new EditorLine(2,"-L-",new(100,0),new(100,100)),new EditorLine(3,"-L-",new(100,100),new(0,100)),new EditorLine(4,"-L-",new(0,100),new(0,0)),new EditorLine(5,"-V-",new(0,40),new(100,40)),new EditorLine(6,"-V1-",new(30,0),new(30,100))]);var y=SectionAnalyzer.Analyze(d,SectionAxis.Y,50);var x=SectionAnalyzer.Analyze(d,SectionAxis.X,50);if(y.Model.Hinges.Count!=1||y.Model.Hinges[0].EntityId!=5||y.Model.Hinges[0].Direction!=BendDirection.Left)Fail("Y section");if(x.Model.Hinges.Count!=1||x.Model.Hinges[0].EntityId!=6||x.Model.Hinges[0].Direction!=BendDirection.Right)Fail("X section");var xs=new BendSimulation(x.Model);var ys=new BendSimulation(y.Model);xs.Bend(6);if(xs.History.Count!=1||ys.History.Count!=0)Fail("independent simulation state");}
static void RoundTrip(){var path=Path.Combine(Path.GetTempPath(),$"drawer-{Guid.NewGuid():N}.dxf");try{var d=new DrawingDocument();d.Entities.AddRange([new EditorLine(1,"-L-",new(0,0),new(100,0)),new EditorArc(2,"-L-",new(50,20),10,0,180),new EditorCircle(3,"-L-",new(20,20),5),new EditorLine(4,"-V-",new(0,10),new(100,10)),new EditorLine(5,"-V1-",new(0,15),new(100,15))]);DxfWriter.Save(d,path);var parsed=DxfDocumentParser.Parse(path);if(parsed.Entities.Count!=5||!parsed.Layers.SetEquals(["-L-","-V-","-V1-"]))Fail("DXF roundtrip");}finally{if(File.Exists(path))File.Delete(path);}}
static void Eq(double a,double b){if(Math.Abs(a-b)>1e-6)Fail($"{a}!={b}");}static void Fail(string s)=>throw new InvalidOperationException(s);
static double Distance(DxfPoint a,DxfPoint b){var x=a.X-b.X;var y=a.Y-b.Y;return Math.Sqrt(x*x+y*y);}
