using System.IO;
using System.Windows;
using VCutting;
using Localization=VCutting.Localization;

static class CutUnionTests
{
    static void Check(bool ok,string reason){if(!ok)throw new InvalidOperationException(reason);}
    static CutOperation Add(VCuttingDocument d,string shape,double x,double y,double w,double h){var c=d.AddHole(shape,x,y);d.UpdateCut(c,x,y,w,h,7);return c;}
    public static void Run()
    {
        var d=new VCuttingDocument();var left=Add(d,"Circle",90,80,60,60);var bridge=Add(d,"Rectangle",150,80,120,40);var right=Add(d,"Circle",210,80,60,60);var independent=Add(d,"Ellipse",150,210,80,40);
        Check(d.InternalMergeGroup(bridge).Count==3,"transitive circle-rectangle-circle group");var outer=d.OuterContour.Segments.ToArray();var history=new UndoRedoManager();history.Record(d);
        var mask=FlatMaterialMaskEngine.Build(d,new(1,new(0,300)));Check(!mask.FillContains(new Point(95,220)),"overlap is removed before merge");
        Check(d.TryMergeInternalCuts(bridge),"mixed curve merge");Check(d.Cuts.Count==2&&d.Cuts.Contains(independent)&&d.Cuts.Contains(bridge)&&bridge.Shape=="Compound","one retained object, independent unchanged");Check(d.InnerContours.Count==2&&d.InnerContours.Single(c=>c.Id==bridge.Id).Segments.SequenceEqual(bridge.Geometry),"inner contours synced");Check(bridge.Geometry.Any(g=>g is ArcSegment)&&bridge.Geometry.Any(g=>g is LineSegment),"analytic arcs retained");Check(outer.SequenceEqual(d.OuterContour.Segments),"outer unchanged");
        foreach(var p in new[]{new Point(65,80),new Point(150,80),new Point(235,80)})Check(CutContourEngine.Contains(bridge.Geometry,p),"union covers all lobes");Check(!CutContourEngine.Contains(bridge.Geometry,new(150,110)),"union excludes outside");
        var undone=history.Undo(d)!;Check(undone.Cuts.Count==4,"one undo restores entire group");var redone=history.Redo(undone)!;Check(redone.Cuts.Count==2&&redone.Cuts.Any(c=>c.Shape=="Compound"),"redo union");
        var extra=Add(d,"Rectangle",240,80,30,20);Check(d.Cuts.Select(c=>c.Id).Distinct().Count()==3,"new cut ID does not collide");Check(d.TryMergeInternalCuts(bridge)&&d.Cuts.Count==2,"repeat union");
        var radius=bridge.Geometry.OfType<ArcSegment>().First().Radius;Check(!d.CanUpdateCompound(bridge,150,80,bridge.Width*1.1,bridge.Height),"curve nonuniform scale rejected");Check(d.TryUpdateCompound(bridge,150,80,bridge.Width*.8,bridge.Height*.8),"curve uniform scale");Check(Math.Abs(bridge.Geometry.OfType<ArcSegment>().First().Radius-radius*.8)<1e-6,"curve radius scaled exactly");
        foreach(var shape in new[]{"Rectangle","Triangle","Diamond","Parallelogram","Semicircle","QuarterCircle","Ellipse"}){var doc=new VCuttingDocument();var a=Add(doc,shape,140,150,50,40);Add(doc,"Rectangle",150,150,40,40);Check(doc.TryMergeInternalCuts(a),shape+" union");Check(CutContourEngine.Loops(a.Geometry).Count==1,shape+" closed loop");}
        foreach(var same in new[]{false,true}){var doc=new VCuttingDocument();var a=Add(doc,"Circle",150,150,60,60);Add(doc,"Circle",150,150,same?60:20,same?60:20);Check(doc.TryMergeInternalCuts(a),"duplicate/contained circle");Check(CutContourEngine.Contains(a.Geometry,new(150,150)),"circle parity");}
        var rounded=new VCuttingDocument();var roundedCut=Add(rounded,"Rectangle",140,150,60,60);Check(rounded.TryFilletContourCorner(roundedCut.Id,0,5,out _),"filleted union fixture");Add(rounded,"Rectangle",165,150,40,40);Check(rounded.TryMergeInternalCuts(roundedCut)&&roundedCut.Geometry.Any(g=>g is ArcSegment),"filleted cut union preserves arc");
        var transitive=new VCuttingDocument();var first=Add(transitive,"Rectangle",90,150,50,40);Add(transitive,"Rectangle",130,150,50,40);Add(transitive,"Rectangle",170,150,50,40);Check(transitive.InternalMergeGroup(first).Count==3&&transitive.TryMergeInternalCuts(first)&&transitive.Cuts.Count==1,"transitive bridge without direct end overlap");
        var edge=new VCuttingDocument();var e=Add(edge,"Rectangle",100,100,40,40);Add(edge,"Rectangle",140,100,40,40);Check(edge.TryMergeInternalCuts(e),"shared edge union");
        foreach(var distance in new[]{40d,41d}){var doc=new VCuttingDocument();var a=Add(doc,"Circle",100,100,40,40);Add(doc,"Circle",100+distance,100,40,40);Check(!doc.TryMergeInternalCuts(a)&&doc.Cuts.Count==2,"point tangent/disjoint rejected");}
        var corner=new VCuttingDocument();var cc=Add(corner,"Rectangle",100,100,40,40);Add(corner,"Rectangle",140,140,40,40);Check(!corner.TryMergeInternalCuts(cc),"point-only corners rejected");
        var boundary=new VCuttingDocument();var bc=Add(boundary,"Rectangle",20,100,40,40);Add(boundary,"Circle",30,100,30,30);Check(!boundary.CanMergeInternalCuts(bc)&&boundary.CanMergeBoundaryCut(bc),"outer workflow stays separate");
        var ring=new VCuttingDocument();var top=Add(ring,"Rectangle",150,190,100,30);Add(ring,"Rectangle",150,110,100,30);Add(ring,"Rectangle",110,150,30,100);Add(ring,"Rectangle",190,150,30,100);Check(ring.TryMergeInternalCuts(top),"ring union");Check(CutContourEngine.Loops(top.Geometry).Count==2,"material island preserved as second loop");Check(!CutContourEngine.Contains(top.Geometry,new(150,150))&&CutContourEngine.Contains(top.Geometry,new(110,150)),"ring parity");mask=FlatMaterialMaskEngine.Build(ring,new(1,new(0,300)));Check(mask.FillContains(new Point(150,150))&&!mask.FillContains(new Point(110,150)),"flat ring island");var mesh=BentSurfaceEngine.Build(ring);var area=0d;var island=false;for(var i=0;i<mesh.Triangles.Count;i+=3){var a=mesh.Points[mesh.Triangles[i]];var b=mesh.Points[mesh.Triangles[i+1]];var c=mesh.Points[mesh.Triangles[i+2]];area+=Math.Abs((b.X-a.X)*(c.Y-a.Y)-(b.Y-a.Y)*(c.X-a.X))/2;var mid=new Point((a.X+b.X+c.X)/3,(a.Y+b.Y+c.Y)/3);Check(!CutContourEngine.Contains(top.Geometry,mid),"3D removed ring faces");if(mid.X>125&&mid.X<175&&mid.Y>125&&mid.Y<175)island=true;}Check(Math.Abs(area-80500)<1e-6&&island,"3D exact ring area and material island");Check(!ring.TryFilletContourCorner(top.Id,0,2,out _),"multi-loop fillet safely rejected");Check(ring.TryUpdateCompound(top,150,150,top.Width*.9,top.Height*.8),"line compound affine scaling");
        var path=Path.Combine(Path.GetTempPath(),"cut-union-"+Guid.NewGuid().ToString("N")+".dxf");try{VCuttingDxfSerializer.Save(ring,path);var loaded=VCuttingDxfSerializer.Load(path);Check(loaded.Cuts.Single().Geometry.SequenceEqual(top.Geometry)&&CutContourEngine.Loops(loaded.Cuts.Single().Geometry).Count==2,"multi-loop DXF metadata roundtrip");var oldWidth=top.Width;ring.ChangeUnit(MeasurementUnit.Millimeter,UnitChangeMode.PreservePhysicalSize);Check(Math.Abs(top.Width-oldWidth*10)<1e-6&&CutContourEngine.Loops(top.Geometry).Count==2,"compound units preserve geometry");}finally{File.Delete(path);}
        foreach(var lang in new[]{"en","ko"}){Localization.SetLanguage(lang);Check(Localization.Text("merge.internal")!="merge.internal"&&Localization.Kind("Compound")!="Compound","localized merge");}Localization.SetLanguage("en");
    }
}
