<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CosmicDesigner</AssemblyName>
    <Version>1.20.29</Version>
    <ApplicationIcon>Resources\cosmic_dmi.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DXFExplorer\DXFExplorer.csproj" />
    <Resource Include="Resources\cosmic_dmi.ico" />
    <Resource Include="Resources\cosmic_dmi.svg" />
    <Resource Include="Resources\slit-*.png" />
  </ItemGroup>
</Project>
