using Microsoft.Win32;
using System.Diagnostics;
using System.Globalization;
using System.Windows;
using System.Windows.Controls;

namespace CosmicDesigner;

public partial class MainWindow : Window
{
    CosmicDesignerDocument _document = new(); string? _path; string? _titlePath;
    readonly DocumentDirtyState _dirtyState=new();
    readonly UndoRedoManager _history=new(100);
    readonly CosmicDesignerSettings _settings=UserSettingsStore.Load();
    public MainWindow(){InitializeComponent();_dirtyState.StateChanged+=(_,_)=>Dispatcher.Invoke(UpdateWindowTitle);ApplyUserPreferences();ApplyGlobalViewSettings();ApplySectionDefaults(_document);RebuildRecentMenu();Attach(_document);PreviewKeyDown+=MainWindow_PreviewKeyDown;Closing+=MainWindow_Closing;}
    void Attach(CosmicDesignerDocument document)
    {
        _document=document;FlatView.Document=document;FlatView.SelectedObject=null;FlatView.ResetSectionPositions();WSection.Document=document;WSection.SelectedObject=null;WSection.SectionPosition=FlatView.WSectionPosition;HSection.Document=document;HSection.SelectedObject=null;HSection.SectionPosition=FlatView.HSectionPosition;Preview3D.Document=document;WDimensions.IsChecked=document.WView.Dimensions;WBent.IsChecked=document.WView.BentMode;HDimensions.IsChecked=document.HView.Dimensions;HBent.IsChecked=document.HView.BentMode;WSection.ShowDimensions=document.WView.Dimensions;WSection.BentMode=document.WView.BentMode;WSection.SetRotation(document.WView.RotationQuarterTurns);HSection.ShowDimensions=document.HView.Dimensions;HSection.BentMode=document.HView.BentMode;HSection.SetRotation(document.HView.RotationQuarterTurns);
        document.Changed+=DocumentChanged;WSection.BendCreated-=BendCreated;HSection.BendCreated-=BendCreated;WSection.BeforeEdit-=BeforeDocumentEdit;HSection.BeforeEdit-=BeforeDocumentEdit;FlatView.HolePlacementRequested-=HolePlacementRequested;FlatView.BeforeEdit-=BeforeDocumentEdit;FlatView.PointerPositionChanged-=FlatPointerChanged;FlatView.ObjectSelected-=FlatObjectSelected;FlatView.HoleToolCancelled-=FlatHoleToolCancelled;FlatView.SectionSelectionChanged-=FlatSectionSelectionChanged;FlatView.BoundaryMergeRequested-=BoundaryMergeRequested;WSection.BendCreated+=BendCreated;HSection.BendCreated+=BendCreated;WSection.BeforeEdit+=BeforeDocumentEdit;HSection.BeforeEdit+=BeforeDocumentEdit;FlatView.HolePlacementRequested+=HolePlacementRequested;FlatView.BeforeEdit+=BeforeDocumentEdit;FlatView.PointerPositionChanged+=FlatPointerChanged;FlatView.ObjectSelected+=FlatObjectSelected;FlatView.HoleToolCancelled+=FlatHoleToolCancelled;FlatView.SectionSelectionChanged+=FlatSectionSelectionChanged;FlatView.BoundaryMergeRequested+=BoundaryMergeRequested;SyncSectionMenus();RefreshAll();UpdateHistoryUi();
    }
    void DocumentChanged(object? sender,EventArgs e){_dirtyState.MarkChanged();Dispatcher.Invoke(()=>{UpdateWindowTitle();RefreshAll();});}
    void BeforeDocumentEdit(object? sender,EventArgs e)=>RecordEdit();
    void RecordEdit(){_history.Record(_document);UpdateHistoryUi();}
    void UpdateHistoryUi(){UndoMenu.IsEnabled=_history.CanUndo;RedoMenu.IsEnabled=_history.CanRedo;}
    void UpdateWindowTitle()=>Title=WindowTitleFormatter.Format(_titlePath,_dirtyState.IsDirty);
    void BendCreated(object? sender,BendObject e){ShowProperties(e);StatusText.Text=$"Created {e.Id} on {e.Layer} layer";RefreshAll();}
    void RefreshAll()
    {
        ApplyRulerGridPreferences();
        WidthBox.Text=_document.Material.Width.ToString("0.###",CultureInfo.CurrentCulture);HeightBox.Text=_document.Material.Height.ToString("0.###",CultureInfo.CurrentCulture);ThicknessBox.Text=_document.Material.Thickness.ToString("0.###",CultureInfo.CurrentCulture);if(WidthBox.Parent is Grid grid&&grid.Parent is GroupBox group)group.Header=$"Material ({_document.Unit.Symbol()})";
        ObjectTree.Items.Clear();var material=new TreeViewItem{Header="Material",Tag=_document.Material};var outer=new TreeViewItem{Header="Outer Contour",Tag=_document.OuterContour};var gi=1;foreach(var g in _document.OuterContour.Segments){var go=new GeometryObject{Id=$"L{gi:000}",Sequence=gi,Layer="L",EntityType=g switch{LineSegment=>"LINE",ArcSegment=>"ARC",_=>"CIRCLE"},Geometry=g};outer.Items.Add(new TreeViewItem{Header=$"{gi:000} L {go.EntityType} {go.Id}",Tag=go});gi++;}material.Items.Add(outer);
        var v=new TreeViewItem{Header=$"V Objects ({_document.Bends.Count(x=>x.Layer=="V")})"};foreach(var b in _document.Bends.Where(x=>x.Layer=="V").OrderBy(x=>x.Sequence))v.Items.Add(new TreeViewItem{Header=$"{b.Sequence:000} V {b.Id}",Tag=b});material.Items.Add(v);
        var v1=new TreeViewItem{Header=$"V1 Objects ({_document.Bends.Count(x=>x.Layer=="V1")})"};foreach(var b in _document.Bends.Where(x=>x.Layer=="V1").OrderBy(x=>x.Sequence))v1.Items.Add(new TreeViewItem{Header=$"{b.Sequence:000} V1 {b.Id}",Tag=b});material.Items.Add(v1);
        var sections=new TreeViewItem{Header="Section Segments"};var ws=new TreeViewItem{Header="W Segments"};foreach(var s in _document.WSegments)ws.Items.Add(new TreeViewItem{Header=$"{s.Id}  {s.Length:0.###} cm",Tag=s});var hs=new TreeViewItem{Header="H Segments"};foreach(var s in _document.HSegments)hs.Items.Add(new TreeViewItem{Header=$"{s.Id}  {s.Length:0.###} cm",Tag=s});sections.Items.Add(ws);sections.Items.Add(hs);material.Items.Add(sections);
        var cuts=new TreeViewItem{Header=$"Cut Objects ({_document.Cuts.Count})"};foreach(var c in _document.Cuts)cuts.Items.Add(new TreeViewItem{Header=$"{c.Sequence:000} L {c.Shape} {c.Id}",Tag=c});material.Items.Add(cuts);cuts.IsExpanded=true;
        var joints=new TreeViewItem{Header=$"Micro Joints ({_document.MicroJoints.Count})"};foreach(var j in _document.MicroJoints)joints.Items.Add(new TreeViewItem{Header=$"{j.Sequence:000} {j.Id}",Tag=j});material.Items.Add(joints);ObjectTree.Items.Add(material);material.IsExpanded=true;outer.IsExpanded=true;v.IsExpanded=true;v1.IsExpanded=true;
        if(FlatView.SelectedObject is { } selected)SelectTreeObject(selected.Id);FlatView.Refresh();WSection.Refresh();HSection.Refresh();Preview3D.Refresh();
    }
    void New_Click(object sender,RoutedEventArgs e){if(!ConfirmSaveChanges())return;_path=null;_titlePath=null;_history.Clear();var document=new CosmicDesignerDocument();document.ConfigureNew(_settings.NewWidth,_settings.NewHeight,_settings.NewThickness,_settings.DefaultUnit);ApplySectionDefaults(document);Attach(document);_dirtyState.MarkSaved();UpdateWindowTitle();StatusText.Text="New design";}
    void Open_Click(object sender,RoutedEventArgs e){if(!ConfirmSaveChanges())return;var d=new OpenFileDialog{Filter="DXF files (*.dxf)|*.dxf",InitialDirectory=ValidFolder(_settings.DefaultOpenFolder)};if(d.ShowDialog()==true)OpenPath(d.FileName);}
    void OpenPath(string fileName){try{CosmicDesignerDocument opened;string status;var plainImport=false;if(CosmicDxfSerializer.HasMetadata(fileName)){opened=CosmicDxfSerializer.Load(fileName);status=$"Design restored in {opened.Unit.Symbol()}";}else{if(MessageBox.Show(this,"CosmicDesigner 메타데이터가 없는 일반 DXF입니다.\n\nL 레이어의 가장 큰 닫힌 형상을 외곽선으로, 나머지 L 형상을 구멍으로 가져오고 V/V1 선을 절곡선으로 변환합니다. DXF 단위를 확인하여 새 문서 기본 단위로 환산하며 재료 두께는 0.2 cm 상당으로 시작합니다.\n\n자동으로 가져오시겠습니까?","DXF 자동 가져오기",MessageBoxButton.OKCancel,MessageBoxImage.Question)!=MessageBoxResult.OK)return;var imported=GeneralDxfImportEngine.Import(fileName);opened=imported.Document;if(opened.Unit!=_settings.DefaultUnit)opened.ChangeUnit(_settings.DefaultUnit,UnitChangeMode.PreservePhysicalSize);ApplySectionDefaults(opened);plainImport=true;status=$"DXF imported in {opened.Unit.Symbol()}: outer {imported.OuterEntities}, cuts {imported.CutObjects}, bends {imported.BendObjects} — Save As required";if(imported.Warnings.Count>0)MessageBox.Show(this,string.Join(Environment.NewLine,imported.Warnings),"DXF 가져오기 경고",MessageBoxButton.OK,MessageBoxImage.Warning);}_history.Clear();Attach(opened);_path=plainImport?null:fileName;_titlePath=fileName;_dirtyState.MarkSaved();UpdateWindowTitle();StatusText.Text=status;UserSettingsStore.AddRecent(_settings,fileName);RebuildRecentMenu();}catch(Exception ex){MessageBox.Show(this,ex.Message,"Open",MessageBoxButton.OK,MessageBoxImage.Error);}}
    void Save_Click(object sender,RoutedEventArgs e)=>TrySaveCurrent();
    void SaveAs_Click(object sender,RoutedEventArgs e)=>TrySaveAs();
    bool TrySaveCurrent()=>_path is null?TrySaveAs():SaveTo(_path);
    bool TrySaveAs(){var d=new SaveFileDialog{Filter="DXF files (*.dxf)|*.dxf",DefaultExt=".dxf",FileName="CosmicDesign.dxf",InitialDirectory=ValidFolder(_settings.DefaultSaveFolder)};if(d.ShowDialog()!=true)return false;_path=d.FileName;return SaveTo(_path);}
    bool SaveTo(string path){try{SyncSectionViewState();CosmicDxfSerializer.Save(_document,path);_titlePath=path;_dirtyState.MarkSaved();UpdateWindowTitle();StatusText.Text="Saved CAM geometry, section views and CosmicDesigner metadata";UserSettingsStore.AddRecent(_settings,path);RebuildRecentMenu();return true;}catch(Exception ex){MessageBox.Show(this,ex.Message,"Save",MessageBoxButton.OK,MessageBoxImage.Error);return false;}}
    void Exit_Click(object sender,RoutedEventArgs e)=>Close();
    bool ConfirmSaveChanges(){if(!_dirtyState.IsDirty)return true;var result=MessageBox.Show(this,"현재 파일에 저장되지 않은 변경 사항이 있습니다.\n\n현재 파일을 저장하시겠습니까?","변경 사항 저장",MessageBoxButton.YesNoCancel,MessageBoxImage.Warning);return result switch{MessageBoxResult.Yes=>TrySaveCurrent(),MessageBoxResult.No=>true,_=>false};}
    void MainWindow_Closing(object? sender,System.ComponentModel.CancelEventArgs e){if(!ConfirmSaveChanges())e.Cancel=true;}
    void Thickness_LostFocus(object sender,RoutedEventArgs e)
    {
        if(!double.TryParse(ThicknessBox.Text,NumberStyles.Float,CultureInfo.CurrentCulture,out var value)||value<=0){ThicknessBox.Text=_document.Material.Thickness.ToString(CultureInfo.CurrentCulture);return;}if(Math.Abs(value-_document.Material.Thickness)<1e-9)return;
        var message=$"Material Thickness change\n\n{_document.Material.Thickness:0.###} cm → {value:0.###} cm\n\nVCut depth, residual thickness, bend positions, flat W/H and 3D preview will be recalculated.";
        if(MessageBox.Show(this,message,"Apply thickness change",MessageBoxButton.OKCancel,MessageBoxImage.Warning)==MessageBoxResult.OK){RecordEdit();_document.ChangeThickness(value);StatusText.Text="Thickness-dependent values recalculated";}else ThicknessBox.Text=_document.Material.Thickness.ToString(CultureInfo.CurrentCulture);
    }
    void ViewOption_Click(object sender,RoutedEventArgs e){WSection.ShowDimensions=WDimensions.IsChecked==true;HSection.ShowDimensions=HDimensions.IsChecked==true;WSection.BentMode=WBent.IsChecked==true;HSection.BentMode=HBent.IsChecked==true;Preview3D.Transparent=Transparent3D.IsChecked==true;SyncSectionViewState();if(sender is Button)Preview3D.ResetView();SyncSectionMenus();WSection.Refresh();HSection.Refresh();Preview3D.Refresh();}
    void RotateSection_Click(object sender,RoutedEventArgs e){if(sender is Button{Tag:"W"})WSection.RotateClockwise();else if(sender is Button{Tag:"H"})HSection.RotateClockwise();SyncSectionViewState();SyncSectionMenus();StatusText.Text="Section view rotated 90° clockwise";}
    void HoleTool_Click(object sender,RoutedEventArgs e){var shape=(sender as Button)?.Tag as string;FlatView.ActiveHoleShape=shape;SelectModeButton.IsChecked=false;FlatView.Cursor=System.Windows.Input.Cursors.Cross;FlatView.Focus();FlatView.Refresh();StatusText.Text=$"{shape} hole: click inside material";}
    void SelectMode_Click(object sender,RoutedEventArgs e){ActivateSelectMode("Selection mode");}
    void ActivateSelectMode(string status){FlatView.ActiveHoleShape=null;SelectModeButton.IsChecked=true;FlatView.Cursor=System.Windows.Input.Cursors.Arrow;FlatView.Refresh();StatusText.Text=status;}
    void FlatHoleToolCancelled(object? sender,EventArgs e)=>ActivateSelectMode("Hole tool cancelled");
    void HolePlacementRequested(object? sender,HolePlacementEventArgs e){RecordEdit();var cut=_document.AddHole(e.Shape,e.X,e.Y);FlatView.SelectedObject=cut;WSection.SelectedObject=cut;HSection.SelectedObject=cut;RefreshAll();SelectTreeObject(cut.Id);ShowProperties(cut);StatusText.Text=_document.CanMergeBoundaryCut(cut)?"Outer Contour와 통합 가능 — 우클릭하여 통합":"Created L layer "+e.Shape+" hole "+cut.Id;}
    void BoundaryMergeRequested(object? sender,CutOperation cut){if(!_document.CanMergeBoundaryCut(cut))return;RecordEdit();if(!_document.TryMergeBoundaryCut(cut))return;FlatView.SelectedObject=_document.OuterContour;WSection.SelectedObject=_document.OuterContour;HSection.SelectedObject=_document.OuterContour;RefreshAll();SelectTreeObject(_document.OuterContour.Id);ShowProperties(_document.OuterContour);StatusText.Text="Rectangle Cut merged into Outer Contour — Undo available";}
    void FlatPointerChanged(object? sender,PointerPositionEventArgs e)=>PointerText.Text=e.InsideMaterial?$"X {e.X:0.###}  Y {e.Y:0.###} {_document.Unit.Symbol()}":$"X —  Y — {_document.Unit.Symbol()}";
    void FlatSectionSelectionChanged(object? sender,SectionSelectionChangedEventArgs e){var view=e.Axis==SectionAxis.H?HSection:WSection;view.SectionPosition=e.Position;view.Refresh();StatusText.Text=$"{e.Axis} Section moved to {(e.Axis==SectionAxis.H?"X":"Y")} {e.Position:0.###} cm";}
    void FlatObjectSelected(object? sender,DesignObject e){FlatView.SelectedObject=e;WSection.SelectedObject=e;HSection.SelectedObject=e;SelectTreeObject(e.Id);ShowProperties(e);FlatView.Refresh();WSection.Refresh();HSection.Refresh();StatusText.Text=e is CutOperation cut&&_document.CanMergeBoundaryCut(cut)?"Outer Contour와 통합 가능 — 우클릭하여 통합":$"Selected {e.Id}";}
    void ObjectTree_SelectedItemChanged(object sender,RoutedPropertyChangedEventArgs<object> e){if(e.NewValue is not TreeViewItem{Tag:DesignObject o})return;FlatView.SelectedObject=o;WSection.SelectedObject=o;HSection.SelectedObject=o;FlatView.Refresh();WSection.Refresh();HSection.Refresh();ShowProperties(o);StatusText.Text=$"Selected {o.Id}";}
    void ShowProperties(DesignObject o)
    {
        PropertyPanel.Children.Clear();ReadOnlyRow("ID",o.Id);
        if(o is MaterialModel m){var u=_document.Unit.Symbol();ReadOnlyRow($"Flat W ({u})",m.Width);ReadOnlyRow($"Flat H ({u})",m.Height);EditNumber($"Thickness D ({u})",m.Thickness,v=>{if(v<=0)return;var message=$"Material Thickness change\n\n{m.Thickness:0.###} {u} → {v:0.###} {u}\n\nV-Cut depth, residual thickness, bend positions, Flat W/H and 3D preview will be recalculated.";if(MessageBox.Show(this,message,"Apply thickness change",MessageBoxButton.OKCancel,MessageBoxImage.Warning)==MessageBoxResult.OK){RecordEdit();_document.ChangeThickness(v);}});}
        else if(o is BendObject b){ReadOnlyRow("Axis",b.Axis);EditChoice("Direction",b.Direction,Enum.GetValues<BendDirection>(),v=>{RecordEdit();_document.UpdateBend(b,b.Position,v,b.Sequence);});EditNumber(b.Axis==SectionAxis.W?"X Position (cm)":"Y Position (cm)",b.Position,v=>{RecordEdit();_document.UpdateBend(b,v,b.Direction,b.Sequence);});ReadOnlyRow("Bend Angle",b.BendAngle);ReadOnlyRow("V-Cut Angle",b.VCutAngle);ReadOnlyRow("V-Cut Depth (cm)",b.VCutDepth);ReadOnlyRow("Residual (cm)",b.ResidualThickness);EditNumber("Sequence",b.Sequence,v=>{RecordEdit();_document.UpdateBend(b,b.Position,b.Direction,(int)v);});}
        else if(o is SectionSegment s){ReadOnlyRow("Axis",s.Axis);EditNumber("Length (cm)",s.Length,v=>{RecordEdit();_document.UpdateSegment(s,v);});}
        else if(o is GeometryObject g){ReadOnlyRow("Layer",g.Layer);ReadOnlyRow("Entity",g.EntityType);if(g.Geometry is LineSegment l){ReadOnlyRow("X1",l.X1);ReadOnlyRow("Y1",l.Y1);ReadOnlyRow("X2",l.X2);ReadOnlyRow("Y2",l.Y2);}}
        else if(o is CutOperation c){ReadOnlyRow("Layer","L");ReadOnlyRow("Shape",c.Shape);EditNumber("Center X (cm)",c.CenterX,v=>{RecordEdit();_document.UpdateCut(c,v,c.CenterY,c.Width,c.Height,c.Sides);});EditNumber("Center Y (cm)",c.CenterY,v=>{RecordEdit();_document.UpdateCut(c,c.CenterX,v,c.Width,c.Height,c.Sides);});EditNumber("Width (cm)",c.Width,v=>{RecordEdit();_document.UpdateCut(c,c.CenterX,c.CenterY,v,c.Height,c.Sides);});EditNumber("Height (cm)",c.Height,v=>{RecordEdit();_document.UpdateCut(c,c.CenterX,c.CenterY,c.Width,v,c.Sides);});if(c.Shape=="Polygon")EditNumber("Sides",c.Sides,v=>{RecordEdit();_document.UpdateCut(c,c.CenterX,c.CenterY,c.Width,c.Height,(int)v);});}
        else if(o is MicroJoint j){ReadOnlyRow("Parent",j.ParentContourId);EditNumber("Position (cm)",j.Position,v=>{RecordEdit();j.Position=v;_document.Recalculate();});EditNumber("Width (cm)",j.Width,v=>{if(v>0){RecordEdit();j.Width=v;_document.Recalculate();}});}
    }
    void ReadOnlyRow(string name,object value)=>AddRow(name,new TextBox{Text=Convert.ToString(value,CultureInfo.CurrentCulture),IsReadOnly=true,Background=System.Windows.Media.Brushes.Gainsboro});
    void EditNumber(string name,double value,Action<double> apply){var box=new TextBox{Text=value.ToString("0.###",CultureInfo.CurrentCulture)};box.LostFocus+=(_,_)=>{if(double.TryParse(box.Text,NumberStyles.Float,CultureInfo.CurrentCulture,out var v)){apply(v);StatusText.Text=$"{name} updated";}else{box.Text=value.ToString(CultureInfo.CurrentCulture);StatusText.Text=$"Invalid {name}";}};AddRow(name,box);}
    void EditChoice<T>(string name,T value,IEnumerable<T> values,Action<T> apply){var box=new ComboBox{ItemsSource=values,SelectedItem=value};box.SelectionChanged+=(_,_)=>{if(box.SelectedItem is T v)apply(v);};AddRow(name,box);}
    void AddRow(string name,Control editor){var grid=new Grid{Margin=new Thickness(0,2,0,2)};grid.ColumnDefinitions.Add(new ColumnDefinition());grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(112)});grid.Children.Add(new TextBlock{Text=name,VerticalAlignment=VerticalAlignment.Center});Grid.SetColumn(editor,1);grid.Children.Add(editor);PropertyPanel.Children.Add(grid);}
    void Undo_Click(object sender,RoutedEventArgs e){var restored=_history.Undo(_document);if(restored is null)return;Attach(restored);_dirtyState.MarkChanged();UpdateWindowTitle();StatusText.Text="Undo completed";UpdateHistoryUi();}
    void Redo_Click(object sender,RoutedEventArgs e){var restored=_history.Redo(_document);if(restored is null)return;Attach(restored);_dirtyState.MarkChanged();UpdateWindowTitle();StatusText.Text="Redo completed";UpdateHistoryUi();}
    void MainWindow_PreviewKeyDown(object sender,System.Windows.Input.KeyEventArgs e){if(e.Key==System.Windows.Input.Key.Delete&&(ObjectTree.IsKeyboardFocusWithin||FlatView.IsKeyboardFocusWithin)){DeleteSelectedObject(FlatView.IsKeyboardFocusWithin?FlatView.SelectedObject:null);e.Handled=true;return;}var fileAction=FileShortcutEngine.Resolve(e.Key,System.Windows.Input.Keyboard.Modifiers);if(fileAction!=FileShortcutAction.None){if(fileAction==FileShortcutAction.New)New_Click(sender,e);else if(fileAction==FileShortcutAction.Open)Open_Click(sender,e);else Save_Click(sender,e);e.Handled=true;return;}if(System.Windows.Input.Keyboard.Modifiers!=System.Windows.Input.ModifierKeys.Control)return;if(e.Key==System.Windows.Input.Key.Z){Undo_Click(sender,e);e.Handled=true;}else if(e.Key==System.Windows.Input.Key.Y){Redo_Click(sender,e);e.Handled=true;}else if(e.Key==System.Windows.Input.Key.OemComma){Settings_Click(sender,e);e.Handled=true;}}
    void DeleteSelectedObject(DesignObject? requested=null){var selected=requested??(ObjectTree.SelectedItem as TreeViewItem)?.Tag as DesignObject;if(selected is null)return;if(selected is MaterialModel or ContourObject or SectionSegment){StatusText.Text="This structural item cannot be deleted";return;}RecordEdit();if(!_document.DeleteObject(selected)){var restored=_history.Undo(_document);if(restored is not null)Attach(restored);StatusText.Text="Selected item cannot be deleted";return;}PropertyPanel.Children.Clear();FlatView.SelectedObject=null;WSection.SelectedObject=null;HSection.SelectedObject=null;StatusText.Text=$"Deleted {selected.Id} — Undo is available";RefreshAll();UpdateHistoryUi();}
    void Help_Click(object sender,RoutedEventArgs e){var p=System.IO.Path.Combine(AppContext.BaseDirectory,"CosmicDesigner_help.html");if(System.IO.File.Exists(p))Process.Start(new ProcessStartInfo(p){UseShellExecute=true});else MessageBox.Show(this,"Help content is prepared for a future release.","CosmicDesigner Help");}
    void About_Click(object sender,RoutedEventArgs e)=>MessageBox.Show(this,"CosmicDesigner 1.15.0\nSection-driven sheet-metal design","About",MessageBoxButton.OK,MessageBoxImage.Information);
    void ZoomIn_Click(object sender,RoutedEventArgs e)=>FlatView.ZoomIn();void ZoomOut_Click(object sender,RoutedEventArgs e)=>FlatView.ZoomOut();void Fit_Click(object sender,RoutedEventArgs e)=>FlatView.FitToWindow();
    void GlobalViewOption_Click(object sender,RoutedEventArgs e){_settings.ShowRuler=RulerMenu.IsChecked;_settings.ShowGrid=GridMenu.IsChecked;_settings.ShowStatusBar=StatusBarMenu.IsChecked;UserSettingsStore.Save(_settings);ApplyGlobalViewSettings();}
    void FlatDisplayButton_Click(object sender,RoutedEventArgs e){_settings.ShowRuler=RulerButton.IsChecked==true;_settings.ShowGrid=GridButton.IsChecked==true;UserSettingsStore.Save(_settings);ApplyGlobalViewSettings();}
    void ApplyGlobalViewSettings(){RulerMenu.IsChecked=_settings.ShowRuler;GridMenu.IsChecked=_settings.ShowGrid;StatusBarMenu.IsChecked=_settings.ShowStatusBar;RulerButton.IsChecked=_settings.ShowRuler;GridButton.IsChecked=_settings.ShowGrid;FlatView.ShowRuler=_settings.ShowRuler;FlatView.ShowGrid=_settings.ShowGrid;MainStatusBar.Visibility=_settings.ShowStatusBar?Visibility.Visible:Visibility.Collapsed;FlatView.Refresh();}
    void ApplyUserPreferences(){var factor=1+_settings.ZoomStepPercent/100;FlatView.ZoomFactor=WSection.ZoomFactor=HSection.ZoomFactor=factor;FlatView.SelectionTolerance=_settings.SelectionTolerancePixels;FlatView.HandleRadius=_settings.HandleRadiusPixels;ApplyRulerGridPreferences();Preview3D.TransparentOpacity=(byte)_settings.Transparent3DOpacity;Preview3D.SolidOpacity=(byte)_settings.Solid3DOpacity;Preview3D.EdgeScale=_settings.Edge3DScale;Transparent3D.IsChecked=_settings.Transparent3DDefault;Preview3D.Transparent=_settings.Transparent3DDefault;}
    void ApplyRulerGridPreferences(){var unitMetres=_document.Unit.Metres();FlatView.HorizontalRulerInterval=_settings.HorizontalRulerIntervalMetres/unitMetres;FlatView.VerticalRulerInterval=_settings.VerticalRulerIntervalMetres/unitMetres;FlatView.GridInterval=_settings.GridIntervalMetres/unitMetres;}
    void Settings_Click(object sender,RoutedEventArgs e){var window=new SettingsWindow(this,_settings,_document.Unit);if(window.ShowDialog()!=true)return;UserSettingsStore.Save(_settings);ApplyUserPreferences();RebuildRecentMenu();FlatView.Refresh();WSection.Refresh();HSection.Refresh();Preview3D.Refresh();StatusText.Text="Settings applied";}
    void DocumentUnits_Click(object sender,RoutedEventArgs e){var window=new DocumentUnitsWindow(this,_document);if(window.ShowDialog()!=true||window.SelectedUnit==_document.Unit)return;var hPosition=FlatView.HSectionPosition;var wPosition=FlatView.WSectionPosition;var factor=window.Mode==UnitChangeMode.PreservePhysicalSize?_document.Unit.Metres()/window.SelectedUnit.Metres():1;RecordEdit();_document.ChangeUnit(window.SelectedUnit,window.Mode);FlatView.SetSectionPositions(hPosition*factor,wPosition*factor);HSection.SectionPosition=FlatView.HSectionPosition;WSection.SectionPosition=FlatView.WSectionPosition;RefreshAll();StatusText.Text=$"Document unit changed to {_document.Unit.Symbol()}";}
    static string ValidFolder(string path)=>System.IO.Directory.Exists(path)?path:"";
    void RebuildRecentMenu(){RecentMenu.Items.Clear();foreach(var path in _settings.RecentFiles.Take(Math.Clamp(_settings.RecentFileCount,1,50))){var item=new MenuItem{Header=path,Tag=path};item.Click+=Recent_Click;RecentMenu.Items.Add(item);}RecentMenu.IsEnabled=RecentMenu.Items.Count>0;}
    void Recent_Click(object sender,RoutedEventArgs e){if(sender is not MenuItem{Tag:string path})return;if(!System.IO.File.Exists(path)){MessageBox.Show(this,"최근 파일을 찾을 수 없어 목록에서 제거합니다.","Recent",MessageBoxButton.OK,MessageBoxImage.Warning);_settings.RecentFiles.RemoveAll(x=>string.Equals(x,path,StringComparison.OrdinalIgnoreCase));UserSettingsStore.Save(_settings);RebuildRecentMenu();return;}if(ConfirmSaveChanges())OpenPath(path);}
    void SyncSectionViewState(){var changed=_document.WView.Dimensions!=(WDimensions.IsChecked==true)||_document.WView.BentMode!=(WBent.IsChecked==true)||_document.WView.RotationQuarterTurns!=WSection.ViewRotationQuarterTurns||_document.HView.Dimensions!=(HDimensions.IsChecked==true)||_document.HView.BentMode!=(HBent.IsChecked==true)||_document.HView.RotationQuarterTurns!=HSection.ViewRotationQuarterTurns;_document.WView.Dimensions=WDimensions.IsChecked==true;_document.WView.BentMode=WBent.IsChecked==true;_document.WView.RotationQuarterTurns=WSection.ViewRotationQuarterTurns;_document.HView.Dimensions=HDimensions.IsChecked==true;_document.HView.BentMode=HBent.IsChecked==true;_document.HView.RotationQuarterTurns=HSection.ViewRotationQuarterTurns;if(changed)_dirtyState.MarkChanged();_settings.WDimensions=_document.WView.Dimensions;_settings.WBent=_document.WView.BentMode;_settings.WRotation=_document.WView.RotationQuarterTurns;_settings.HDimensions=_document.HView.Dimensions;_settings.HBent=_document.HView.BentMode;_settings.HRotation=_document.HView.RotationQuarterTurns;UserSettingsStore.Save(_settings);}
    void ApplySectionDefaults(CosmicDesignerDocument document){document.WView.Dimensions=_settings.WDimensions;document.WView.BentMode=_settings.WBent;document.WView.RotationQuarterTurns=_settings.WRotation;document.HView.Dimensions=_settings.HDimensions;document.HView.BentMode=_settings.HBent;document.HView.RotationQuarterTurns=_settings.HRotation;}
    void SectionMenuOption_Click(object sender,RoutedEventArgs e){WDimensions.IsChecked=WDimensionsMenu.IsChecked;WBent.IsChecked=WBentMenu.IsChecked;HDimensions.IsChecked=HDimensionsMenu.IsChecked;HBent.IsChecked=HBentMenu.IsChecked;ViewOption_Click(sender,e);}
    void SectionRotationMenu_Click(object sender,RoutedEventArgs e){if(sender is not MenuItem{Tag:string tag})return;var parts=tag.Split(':');if(parts.Length!=2||!int.TryParse(parts[1],out var rotation))return;if(parts[0]=="W")WSection.SetRotation(rotation);else HSection.SetRotation(rotation);SyncSectionViewState();SyncSectionMenus();WSection.Refresh();HSection.Refresh();}
    void SyncSectionMenus(){WDimensionsMenu.IsChecked=WDimensions.IsChecked==true;WBentMenu.IsChecked=WBent.IsChecked==true;HDimensionsMenu.IsChecked=HDimensions.IsChecked==true;HBentMenu.IsChecked=HBent.IsChecked==true;}
    void SelectTreeObject(string id){TreeViewItem? Find(ItemsControl parent){foreach(var raw in parent.Items)if(raw is TreeViewItem item){if(item.Tag is DesignObject o&&o.Id==id)return item;var nested=Find(item);if(nested is not null)return nested;}return null;}var found=Find(ObjectTree);if(found is not null){found.IsSelected=true;found.BringIntoView();}}
}
