using System.Globalization;
using System.Windows;
using System.Windows.Controls;

namespace CosmicDesigner;

public sealed class SettingsWindow : Window
{
    readonly CosmicDesignerSettings _target;readonly MeasurementUnit _displayUnit;readonly TextBox _open=new(),_save=new(),_recent=new(),_zoom=new(),_tolerance=new(),_handles=new(),_width=new(),_height=new(),_thickness=new(),_transparentOpacity=new(),_solidOpacity=new(),_edgeScale=new(),_horizontalRuler=new(),_verticalRuler=new(),_gridInterval=new();readonly ComboBox _unit=new(){ItemsSource=Enum.GetValues<MeasurementUnit>()};readonly CheckBox _transparent=new(){Content="새 문서에서 Semi Transparent 3D 사용"};
    public SettingsWindow(Window owner,CosmicDesignerSettings settings,MeasurementUnit displayUnit){Owner=owner;Title="Settings";Width=580;Height=580;WindowStartupLocation=WindowStartupLocation.CenterOwner;ResizeMode=ResizeMode.NoResize;_target=settings;_displayUnit=displayUnit;var tabs=new TabControl();tabs.Items.Add(Tab("General",Rows(("기본 열기 폴더",_open),("기본 저장 폴더",_save),("Recent 파일 개수",_recent))));tabs.Items.Add(Tab("Editing",Rows(("Zoom 단계 (%)",_zoom),("선택 허용 거리 (px)",_tolerance),("핸들 반지름 (px)",_handles))));tabs.Items.Add(Tab("Ruler & Grid",Rows(($"가로 Ruler 기본 간격 ({displayUnit.Symbol()})",_horizontalRuler),($"세로 Ruler 기본 간격 ({displayUnit.Symbol()})",_verticalRuler),($"Grid 기본 간격 ({displayUnit.Symbol()})",_gridInterval))));tabs.Items.Add(Tab("3D Preview",Rows(("반투명 Opacity (20-240)",_transparentOpacity),("불투명 Opacity (20-255)",_solidOpacity),("외곽선 굵기 배율",_edgeScale),("",_transparent))));tabs.Items.Add(Tab("New Document",Rows(("기본 단위",_unit),("기본 폭",_width),("기본 높이",_height),("기본 두께",_thickness))));var buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right,Margin=new Thickness(8)};var defaults=new Button{Content="Restore Defaults",Margin=new Thickness(4),Padding=new Thickness(10,4,10,4)};var ok=new Button{Content="OK",IsDefault=true,Margin=new Thickness(4),Padding=new Thickness(18,4,18,4)};var cancel=new Button{Content="Cancel",IsCancel=true,Margin=new Thickness(4),Padding=new Thickness(14,4,14,4)};defaults.Click+=(_,_)=>LoadValues(new());ok.Click+=(_,_)=>Apply();buttons.Children.Add(defaults);buttons.Children.Add(ok);buttons.Children.Add(cancel);var root=new DockPanel();DockPanel.SetDock(buttons,Dock.Bottom);root.Children.Add(buttons);root.Children.Add(tabs);Content=root;LoadValues(settings);}
    static TabItem Tab(string header,UIElement content)=>new(){Header=header,Content=new ScrollViewer{Content=content,VerticalScrollBarVisibility=ScrollBarVisibility.Auto}};
    static Grid Rows(params (string Label,Control Control)[] rows){var grid=new Grid{Margin=new Thickness(16)};grid.ColumnDefinitions.Add(new(){Width=new GridLength(210)});grid.ColumnDefinitions.Add(new());for(var i=0;i<rows.Length;i++){grid.RowDefinitions.Add(new(){Height=GridLength.Auto});var label=new TextBlock{Text=rows[i].Label,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(4,7,10,7)};var control=rows[i].Control;control.Margin=new Thickness(4,5,4,5);Grid.SetRow(label,i);Grid.SetRow(control,i);Grid.SetColumn(control,1);grid.Children.Add(label);grid.Children.Add(control);}return grid;}
    void LoadValues(CosmicDesignerSettings s){_open.Text=s.DefaultOpenFolder;_save.Text=s.DefaultSaveFolder;_recent.Text=s.RecentFileCount.ToString();_zoom.Text=s.ZoomStepPercent.ToString(CultureInfo.CurrentCulture);_tolerance.Text=s.SelectionTolerancePixels.ToString(CultureInfo.CurrentCulture);_handles.Text=s.HandleRadiusPixels.ToString(CultureInfo.CurrentCulture);_horizontalRuler.Text=IntervalText(s.HorizontalRulerIntervalMetres);_verticalRuler.Text=IntervalText(s.VerticalRulerIntervalMetres);_gridInterval.Text=IntervalText(s.GridIntervalMetres);_unit.SelectedItem=s.DefaultUnit;_width.Text=s.NewWidth.ToString(CultureInfo.CurrentCulture);_height.Text=s.NewHeight.ToString(CultureInfo.CurrentCulture);_thickness.Text=s.NewThickness.ToString(CultureInfo.CurrentCulture);_transparent.IsChecked=s.Transparent3DDefault;_transparentOpacity.Text=s.Transparent3DOpacity.ToString();_solidOpacity.Text=s.Solid3DOpacity.ToString();_edgeScale.Text=s.Edge3DScale.ToString(CultureInfo.CurrentCulture);}
    void Apply(){if(!Try(_recent,1,50,out var recent)||!Try(_zoom,1,100,out var zoom)||!Try(_tolerance,2,30,out var tolerance)||!Try(_handles,3,20,out var handles)||!TryInterval(_horizontalRuler,out var horizontal)||!TryInterval(_verticalRuler,out var vertical)||!TryInterval(_gridInterval,out var grid)||!Try(_width,.000001,double.MaxValue,out var width)||!Try(_height,.000001,double.MaxValue,out var height)||!Try(_thickness,.000001,double.MaxValue,out var thickness)||!Try(_transparentOpacity,20,240,out var transparentOpacity)||!Try(_solidOpacity,20,255,out var solidOpacity)||!Try(_edgeScale,.25,4,out var edge)){MessageBox.Show(this,"설정 값의 범위를 확인하세요. Ruler/Grid 간격은 Auto 또는 양수여야 합니다.","Settings",MessageBoxButton.OK,MessageBoxImage.Warning);return;}_target.DefaultOpenFolder=_open.Text.Trim();_target.DefaultSaveFolder=_save.Text.Trim();_target.RecentFileCount=(int)recent;_target.ZoomStepPercent=zoom;_target.SelectionTolerancePixels=tolerance;_target.HandleRadiusPixels=handles;_target.HorizontalRulerIntervalMetres=horizontal;_target.VerticalRulerIntervalMetres=vertical;_target.GridIntervalMetres=grid;_target.DefaultUnit=_unit.SelectedItem is MeasurementUnit unit?unit:MeasurementUnit.Centimeter;_target.NewWidth=width;_target.NewHeight=height;_target.NewThickness=thickness;_target.Transparent3DDefault=_transparent.IsChecked==true;_target.Transparent3DOpacity=(int)transparentOpacity;_target.Solid3DOpacity=(int)solidOpacity;_target.Edge3DScale=edge;DialogResult=true;}
    static bool Try(TextBox box,double min,double max,out double value)=>double.TryParse(box.Text,NumberStyles.Float,CultureInfo.CurrentCulture,out value)&&value>=min&&value<=max;
    string IntervalText(double metres)=>metres>0?(metres/_displayUnit.Metres()).ToString("0.###",CultureInfo.CurrentCulture):"Auto";
    bool TryInterval(TextBox box,out double metres){if(string.Equals(box.Text.Trim(),"Auto",StringComparison.OrdinalIgnoreCase)){metres=0;return true;}if(double.TryParse(box.Text,NumberStyles.Float,CultureInfo.CurrentCulture,out var value)&&value>0&&double.IsFinite(value)){metres=value*_displayUnit.Metres();return true;}metres=0;return false;}
}

public sealed class DocumentUnitsWindow : Window
{
    readonly MeasurementUnit _current;readonly ComboBox _unit=new(){ItemsSource=Enum.GetValues<MeasurementUnit>()};readonly RadioButton _physical=new(){Content="실제 크기를 유지하고 모든 숫자 환산",IsChecked=true,Margin=new Thickness(4)};readonly RadioButton _numbers=new(){Content="숫자 값을 유지하고 도형 크기 변경",Margin=new Thickness(4)};readonly TextBlock _example=new(){Margin=new Thickness(8),TextWrapping=TextWrapping.Wrap};public MeasurementUnit SelectedUnit=MeasurementUnit.Centimeter;public UnitChangeMode Mode=UnitChangeMode.PreservePhysicalSize;
    public DocumentUnitsWindow(Window owner,CosmicDesignerDocument document){Owner=owner;Title="Document Units";Width=500;Height=300;WindowStartupLocation=WindowStartupLocation.CenterOwner;ResizeMode=ResizeMode.NoResize;_current=document.Unit;_unit.SelectedItem=_current;_unit.SelectionChanged+=(_,_)=>UpdateExample(document.Material.Width);_physical.Checked+=(_,_)=>UpdateExample(document.Material.Width);_numbers.Checked+=(_,_)=>UpdateExample(document.Material.Width);var panel=new StackPanel{Margin=new Thickness(18)};panel.Children.Add(new TextBlock{Text=$"현재 단위: {_current.Symbol()}",FontWeight=FontWeights.Bold,Margin=new Thickness(4)});var row=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(4)};row.Children.Add(new TextBlock{Text="새 단위:",Width=120,VerticalAlignment=VerticalAlignment.Center});row.Children.Add(_unit);panel.Children.Add(row);panel.Children.Add(_physical);panel.Children.Add(_numbers);panel.Children.Add(_example);var buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};var ok=new Button{Content="변경",IsDefault=true,Margin=new Thickness(4),Padding=new Thickness(18,4,18,4)};var cancel=new Button{Content="취소",IsCancel=true,Margin=new Thickness(4),Padding=new Thickness(18,4,18,4)};ok.Click+=(_,_)=>{SelectedUnit=_unit.SelectedItem is MeasurementUnit u?u:_current;Mode=_physical.IsChecked==true?UnitChangeMode.PreservePhysicalSize:UnitChangeMode.PreserveNumbers;DialogResult=true;};buttons.Children.Add(ok);buttons.Children.Add(cancel);panel.Children.Add(buttons);Content=panel;UpdateExample(document.Material.Width);}
    void UpdateExample(double value){var target=_unit.SelectedItem is MeasurementUnit u?u:_current;var converted=value*_current.Metres()/target.Metres();_example.Text=_physical.IsChecked==true?$"예: {value:0.###} {_current.Symbol()} → {converted:0.###} {target.Symbol()}\n실제 제작 크기는 유지됩니다.":$"예: {value:0.###} {_current.Symbol()} → {value:0.###} {target.Symbol()}\n숫자는 유지되며 실제 제작 크기가 변경됩니다.";}
}
