using System.Windows;using System.Windows.Input;using System.Windows.Media;using VCutting.Viewer;
namespace VCutting.Drawer;
public enum DrawTool{Select,Line,Arc,Circle,VLine,V1Line}
public enum DragMode{None,CreateLine,MoveEntity,MoveStartPoint,MoveEndPoint,MoveCircleCenter,ResizeCircle,MoveArcCenter,ResizeArc,MoveArcStartAngle,MoveArcEndAngle,MoveXSection,MoveYSection,Pan}
public sealed class DesignerCanvas:FrameworkElement
{
 DrawingDocument document=new();double scale=3;Vector pan=new(80,500);EditorEntity? selected,original;DragMode dragMode;DxfPoint? dragStart,previewPoint;Point? panStart;bool sectionsInitialized;
 public DrawingDocument Document{get=>document;set{document=value;selected=null;CancelInteraction(false);sectionsInitialized=false;EnsureSections();Fit();Changed?.Invoke(this,EventArgs.Empty);}}
 readonly Dictionary<string,bool> visibility=new(StringComparer.OrdinalIgnoreCase){{"-L-",true},{"-V-",true},{"-V1-",true}};
 public DrawTool Tool{get;private set;}=DrawTool.Select;public string Layer=>GetLayerForTool(Tool)??"-L-";public bool GridVisible{get;set;}=true;public bool GridSnap{get;set;}=true;public bool EndpointSnap{get;set;}=true;public double GridSize{get;set;}=10;
 public EditorEntity? Selected=>selected;public DragMode CurrentDragMode=>dragMode;public double XSectionPosition{get;private set;}public double YSectionPosition{get;private set;}public event EventHandler? Changed,SelectionChanged,ToolChanged,BeforeChange;public event EventHandler<string>? ValidationRejected;public event EventHandler<DxfPoint>? CoordinateChanged;public event EventHandler<(SectionAxis Axis,double Position)>? SectionChanged;
 public DesignerCanvas(){Focusable=true;ClipToBounds=true;Background=Brushes.White;}public Brush Background{get;set;}
 public static string? GetLayerForTool(DrawTool tool)=>tool switch{DrawTool.Line or DrawTool.Arc or DrawTool.Circle=>"-L-",DrawTool.VLine=>"-V-",DrawTool.V1Line=>"-V1-",_=>null};
 public void SetLayerVisible(string layer,bool visible){visibility[layer]=visible;InvalidateVisual();}
 new bool IsVisible(EditorEntity e)=>!visibility.TryGetValue(e.Layer,out var shown)||shown;
 public void SetTool(DrawTool tool){Tool=tool;CancelInteraction(false);ToolChanged?.Invoke(this,EventArgs.Empty);InvalidateVisual();}
 public void Fit(){if(ActualWidth<=0||document.Entities.Count==0){InvalidateVisual();return;}var p=document.Entities.SelectMany(x=>x.Points).ToList();var x0=p.Min(x=>x.X);var x1=p.Max(x=>x.X);var y0=p.Min(x=>x.Y);var y1=p.Max(x=>x.Y);scale=Math.Min((ActualWidth-100)/Math.Max(1,x1-x0),(ActualHeight-100)/Math.Max(1,y1-y0));pan=new(50-x0*scale,ActualHeight-50+y0*scale);InvalidateVisual();}
 public void Zoom(double f,Point? p=null){var at=p??new(ActualWidth/2,ActualHeight/2);var w=World(at);scale=Math.Clamp(scale*f,.02,10000);pan=new(at.X-w.X*scale,at.Y+w.Y*scale);InvalidateVisual();}
 public void DeleteSelected(){if(selected is null)return;BeforeChange?.Invoke(this,EventArgs.Empty);document.Entities.Remove(selected);selected=null;SelectionChanged?.Invoke(this,EventArgs.Empty);Notify();}
 public bool ReplaceSelected(EditorEntity e){if(selected is null)return false;if(e is EditorArc arc)e=arc with{StartAngle=GeometryArc.NormalizeAngle(arc.StartAngle),EndAngle=GeometryArc.NormalizeAngle(arc.EndAngle)};if(Invalid(e)){Reject("L-Layer 절단선과 V/V1 선은 같은 구간에 중첩될 수 없습니다.");return false;}BeforeChange?.Invoke(this,EventArgs.Empty);ReplaceWithoutHistory(e);Notify();return true;}
 public void SelectEntity(int? id){var n=id is null?null:document.Entities.FirstOrDefault(x=>x.Id==id);if(ReferenceEquals(n,selected))return;selected=n;InvalidateVisual();SelectionChanged?.Invoke(this,EventArgs.Empty);}
 public void LocateSelected(){if(selected is null)return;var p=selected.Points.ToList();var x=p.Average(q=>q.X);var y=p.Average(q=>q.Y);if(selected is EditorLine{Length:<=GeometryMath.Epsilon})scale=Math.Max(scale,10);pan=new(ActualWidth/2-x*scale,ActualHeight/2+y*scale);InvalidateVisual();}
 public void CancelInteraction(bool select=true){if(original is not null)ReplaceWithoutHistory(original);dragMode=DragMode.None;dragStart=previewPoint=null;original=null;panStart=null;if(IsMouseCaptured)ReleaseMouseCapture();if(select)SelectTool();InvalidateVisual();}
 protected override void OnRender(DrawingContext dc){dc.DrawRectangle(Background,null,new Rect(RenderSize));if(GridVisible)DrawGrid(dc);if(sectionsInitialized)DrawSections(dc);foreach(var e in document.Entities.Where(IsVisible))DrawEntity(dc,e,ReferenceEquals(e,selected));DrawCreationPreview(dc);if(selected is EditorLine{Length:<=GeometryMath.Epsilon} z&&IsVisible(z))Zero(dc,Screen(z.Start));}
 void DrawCreationPreview(DrawingContext dc){if(dragMode!=DragMode.CreateLine||dragStart is not{} a||previewPoint is not{} b)return;var pen=new Pen(Brushes.DodgerBlue,2){DashStyle=DashStyles.Dash};if(Tool==DrawTool.Circle){var r=Dist(a,b)*scale;dc.DrawEllipse(null,pen,Screen(a),r,r);}else if(Tool==DrawTool.Arc){var radius=Dist(a,b);if(radius>GeometryMath.Epsilon)DrawArc(dc,new EditorArc(0,"-L-",a,radius,Angle(a,b),Angle(a,b)-180),pen);}else dc.DrawLine(pen,Screen(a),Screen(b));Handle(dc,Screen(a),Brushes.DodgerBlue);}
 void DrawSections(DrawingContext dc){var xp=Screen(new(0,XSectionPosition)).Y;var yp=Screen(new(YSectionPosition,0)).X;var xpen=new Pen(Brushes.SeaGreen,1.5){DashStyle=DashStyles.Dash};var ypen=new Pen(Brushes.MediumVioletRed,1.5){DashStyle=DashStyles.Dash};dc.DrawLine(xpen,new(0,xp),new(ActualWidth,xp));dc.DrawLine(ypen,new(yp,0),new(yp,ActualHeight));DrawLabel(dc,"X Section",new(6,Math.Clamp(xp-20,2,ActualHeight-20)),Brushes.SeaGreen);DrawLabel(dc,"Y Section",new(Math.Clamp(yp+5,2,ActualWidth-70),4),Brushes.MediumVioletRed);}
 static void DrawLabel(DrawingContext dc,string text,Point p,Brush b)=>dc.DrawText(new(text,System.Globalization.CultureInfo.CurrentCulture,FlowDirection.LeftToRight,new Typeface("Segoe UI Semibold"),11,b,1),p);
 void DrawGrid(DrawingContext dc){if(GridSize*scale<5)return;var pen=new Pen(new SolidColorBrush(Color.FromRgb(235,238,242)),1);var l=World(new(0,0)).X;var r=World(new(ActualWidth,0)).X;var b=World(new(0,ActualHeight)).Y;var t=World(new(0,0)).Y;for(var x=Math.Floor(l/GridSize)*GridSize;x<=r;x+=GridSize)dc.DrawLine(pen,Screen(new(x,b)),Screen(new(x,t)));for(var y=Math.Floor(b/GridSize)*GridSize;y<=t;y+=GridSize)dc.DrawLine(pen,Screen(new(l,y)),Screen(new(r,y)));}
 void DrawEntity(DrawingContext dc,EditorEntity e,bool on){var c=e.Layer=="-V-"?Colors.Red:e.Layer=="-V1-"?Colors.DodgerBlue:Colors.Black;var pen=new Pen(on?Brushes.Orange:new SolidColorBrush(c),on?3:1.8);switch(e){case EditorLine l:dc.DrawLine(pen,Screen(l.Start),Screen(l.End));if(on){Handle(dc,Screen(l.Start),Brushes.Orange);Handle(dc,Screen(l.End),Brushes.Orange);}break;case EditorCircle q:dc.DrawEllipse(null,pen,Screen(q.Center),q.Radius*scale,q.Radius*scale);if(on)Handle(dc,Screen(q.Center),Brushes.Orange);break;case EditorArc a:DrawArc(dc,a,pen);if(on){Handle(dc,Screen(a.Center),Brushes.Orange);Handle(dc,Screen(a.StartPoint),Brushes.Orange);Handle(dc,Screen(a.EndPoint),Brushes.Orange);}break;}}
 void DrawArc(DrawingContext dc,EditorArc a,Pen pen){var sweep=a.SweepAngle;var steps=Math.Max(8,(int)Math.Ceiling(sweep/5));var g=new StreamGeometry();using(var x=g.Open()){x.BeginFigure(Screen(a.StartPoint),false,false);for(var i=1;i<=steps;i++)x.LineTo(Screen(a.At(a.StartAngle+sweep*i/steps)),true,false);}g.Freeze();dc.DrawGeometry(null,pen,g);}static double Angle(DxfPoint c,DxfPoint p)=>GeometryArc.NormalizeAngle(GeometryMath.RadiansToDegrees(Math.Atan2(p.Y-c.Y,p.X-c.X)));
 static void Handle(DrawingContext d,Point p,Brush b)=>d.DrawEllipse(Brushes.White,new Pen(b,2),p,5,5);static void Zero(DrawingContext d,Point p){var m=new Pen(Brushes.Orange,2);d.DrawLine(m,new(p.X-8,p.Y),new(p.X+8,p.Y));d.DrawLine(m,new(p.X,p.Y-8),new(p.X,p.Y+8));d.DrawRectangle(null,m,new Rect(p.X-5,p.Y-5,10,10));}
 protected override void OnMouseLeftButtonDown(MouseButtonEventArgs e){Focus();var s=e.GetPosition(this);var w=Snap(World(s));if(Tool!=DrawTool.Select){dragMode=DragMode.CreateLine;dragStart=previewPoint=w;CaptureMouse();InvalidateVisual();return;}if(selected is EditorLine l){if((s-Screen(l.Start)).Length<=9){Begin(DragMode.MoveStartPoint,w);return;}if((s-Screen(l.End)).Length<=9){Begin(DragMode.MoveEndPoint,w);return;}}else if(selected is EditorCircle c){if((s-Screen(c.Center)).Length<=9){Begin(DragMode.MoveCircleCenter,w);return;}if(Math.Abs((s-Screen(c.Center)).Length-c.Radius*scale)<=9){Begin(DragMode.ResizeCircle,w);return;}}else if(selected is EditorArc a){if((s-Screen(a.Center)).Length<=9){Begin(DragMode.MoveArcCenter,w);return;}if((s-Screen(a.StartPoint)).Length<=9){Begin(DragMode.MoveArcStartAngle,w);return;}if((s-Screen(a.EndPoint)).Length<=9){Begin(DragMode.MoveArcEndAngle,w);return;}if(Distance(a,s)<=9){Begin(DragMode.ResizeArc,w);return;}}if(sectionsInitialized&&Math.Abs(s.Y-Screen(new(0,XSectionPosition)).Y)<=7){dragMode=DragMode.MoveXSection;CaptureMouse();return;}if(sectionsInitialized&&Math.Abs(s.X-Screen(new(YSectionPosition,0)).X)<=7){dragMode=DragMode.MoveYSection;CaptureMouse();return;}var hit=Hit(s);SelectEntity(hit?.Id);if(hit is EditorLine)Begin(DragMode.MoveEntity,w);else if(hit is EditorCircle q)Begin((s-Screen(q.Center)).Length<=9?DragMode.MoveCircleCenter:DragMode.ResizeCircle,w);else if(hit is EditorArc r)Begin((s-Screen(r.Center)).Length<=9?DragMode.MoveArcCenter:DragMode.ResizeArc,w);}
 protected override void OnMouseRightButtonDown(MouseButtonEventArgs e){dragMode=DragMode.Pan;panStart=e.GetPosition(this);CaptureMouse();e.Handled=true;}
 void Begin(DragMode mode,DxfPoint w){dragMode=mode;dragStart=w;original=selected;BeforeChange?.Invoke(this,EventArgs.Empty);CaptureMouse();}
 protected override void OnMouseMove(MouseEventArgs e){var s=e.GetPosition(this);var raw=World(s);var w=Snap(raw);CoordinateChanged?.Invoke(this,raw);if(e.LeftButton==MouseButtonState.Pressed&&dragMode==DragMode.MoveXSection){XSectionPosition=raw.Y;SectionChanged?.Invoke(this,(SectionAxis.X,XSectionPosition));InvalidateVisual();return;}if(e.LeftButton==MouseButtonState.Pressed&&dragMode==DragMode.MoveYSection){YSectionPosition=raw.X;SectionChanged?.Invoke(this,(SectionAxis.Y,YSectionPosition));InvalidateVisual();return;}if(e.LeftButton==MouseButtonState.Pressed&&dragMode==DragMode.CreateLine){previewPoint=w;InvalidateVisual();return;}if(e.LeftButton==MouseButtonState.Pressed&&original is not null&&dragStart is{} p&&dragMode is DragMode.MoveEntity or DragMode.MoveStartPoint or DragMode.MoveEndPoint or DragMode.MoveCircleCenter or DragMode.ResizeCircle or DragMode.MoveArcCenter or DragMode.ResizeArc or DragMode.MoveArcStartAngle or DragMode.MoveArcEndAngle){ReplaceWithoutHistory(Edit(original,p,w,dragMode));Changed?.Invoke(this,EventArgs.Empty);return;}if(e.RightButton==MouseButtonState.Pressed&&dragMode==DragMode.Pan&&panStart is{} q){pan+=s-q;panStart=s;InvalidateVisual();}}
 protected override void OnMouseLeftButtonUp(MouseButtonEventArgs e){if(dragMode==DragMode.CreateLine&&dragStart is{} a){var b=Snap(World(e.GetPosition(this)));EditorEntity? created=null;if(Tool is DrawTool.Line or DrawTool.VLine or DrawTool.V1Line){if(Tool is DrawTool.VLine or DrawTool.V1Line){var dx=Math.Abs(b.X-a.X);var dy=Math.Abs(b.Y-a.Y);b=dx>=dy?new(b.X,a.Y):new(a.X,b.Y);}var l=new EditorLine(document.NextId,GetLayerForTool(Tool)!,a,b);if(l.Length<=GeometryMath.Epsilon)Reject("선의 길이가 너무 짧아 생성하지 않았습니다.");else if(Invalid(l))Reject("절단선(L-Layer)과 동일한 위치에는 V/V1 선을 만들 수 없습니다.");else created=l;}else{var radius=Dist(a,b);if(radius<=GeometryMath.Epsilon)Reject("반경이 너무 작아 생성하지 않았습니다.");else if(Tool==DrawTool.Circle)created=new EditorCircle(document.NextId,"-L-",a,radius);else{var start=Angle(a,b);created=new EditorArc(document.NextId,"-L-",a,radius,start,GeometryArc.NormalizeAngle(start-180));}}if(created is not null){BeforeChange?.Invoke(this,EventArgs.Empty);document.Entities.Add(created);selected=created;Notify();SelectionChanged?.Invoke(this,EventArgs.Empty);}Finish(true);return;}if(original is not null&&selected is not null&&Invalid(selected)){ReplaceWithoutHistory(original);Reject("L-Layer 절단선과 V/V1 선의 중첩이 허용되지 않아 원래 위치로 복원했습니다.");}Finish(false);Notify();}
 protected override void OnMouseRightButtonUp(MouseButtonEventArgs e)=>Finish(false);protected override void OnMouseWheel(MouseWheelEventArgs e){Zoom(e.Delta>0?1.15:1/1.15,e.GetPosition(this));e.Handled=true;}
 void Finish(bool select){dragMode=DragMode.None;dragStart=previewPoint=null;original=null;panStart=null;if(IsMouseCaptured)ReleaseMouseCapture();if(select)SelectTool();InvalidateVisual();}void SelectTool(){Tool=DrawTool.Select;ToolChanged?.Invoke(this,EventArgs.Empty);}
 EditorEntity Edit(EditorEntity e,DxfPoint a,DxfPoint b,DragMode m){var x=b.X-a.X;var y=b.Y-a.Y;if(e is EditorLine l){if(m==DragMode.MoveStartPoint)return l with{Start=b};if(m==DragMode.MoveEndPoint)return l with{End=b};return l with{Start=new(l.Start.X+x,l.Start.Y+y),End=new(l.End.X+x,l.End.Y+y)};}if(e is EditorCircle c)return m==DragMode.ResizeCircle?c with{Radius=Dist(c.Center,b)}:c with{Center=b};if(e is EditorArc q){if(m==DragMode.ResizeArc)return q with{Radius=Dist(q.Center,b)};if(m==DragMode.MoveArcStartAngle)return q.WithStartAngle(Angle(q.Center,b));if(m==DragMode.MoveArcEndAngle)return q.WithEndAngle(Angle(q.Center,b));return q with{Center=b};}return e;}
 bool Invalid(EditorEntity e)=>e is EditorLine l&&GeometryRules.HasForbiddenCutBendOverlap(l,document.Entities);void Reject(string s)=>ValidationRejected?.Invoke(this,s);void ReplaceWithoutHistory(EditorEntity e){if(selected is null)return;var i=document.Entities.FindIndex(x=>x.Id==selected.Id);if(i>=0)document.Entities[i]=e;selected=e;InvalidateVisual();}
 DxfPoint Snap(DxfPoint p){if(EndpointSnap){var q=document.Entities.SelectMany(x=>x.Points).OrderBy(x=>Dist(x,p)).FirstOrDefault();if(q is not null&&Dist(q,p)*scale<12)return q;}return GridSnap?new(Math.Round(p.X/GridSize)*GridSize,Math.Round(p.Y/GridSize)*GridSize):p;}EditorEntity? Hit(Point p)=>document.Entities.Where(IsVisible).OrderBy(x=>Distance(x,p)).FirstOrDefault(x=>Distance(x,p)<10);double Distance(EditorEntity e,Point p)=>e switch{EditorLine l=>LineDistance(p,Screen(l.Start),Screen(l.End)),EditorCircle c=>Math.Abs((p-Screen(c.Center)).Length-c.Radius*scale),EditorArc a=>Math.Abs((p-Screen(a.Center)).Length-a.Radius*scale),_=>999};static double LineDistance(Point p,Point a,Point b){var v=b-a;var t=v.LengthSquared==0?0:Math.Clamp(Vector.Multiply(p-a,v)/v.LengthSquared,0,1);return(p-(a+t*v)).Length;}static double Dist(DxfPoint a,DxfPoint b){var x=a.X-b.X;var y=a.Y-b.Y;return Math.Sqrt(x*x+y*y);}Point Screen(DxfPoint p)=>new(pan.X+p.X*scale,pan.Y-p.Y*scale);DxfPoint World(Point p)=>new((p.X-pan.X)/scale,(pan.Y-p.Y)/scale);void Notify(){InvalidateVisual();Changed?.Invoke(this,EventArgs.Empty);}
 public void EnsureSections(){if(sectionsInitialized||document.Entities.Count==0)return;var b=document.ToDxfDocument().Bounds;if(b.IsEmpty)return;YSectionPosition=(b.MinX+b.MaxX)/2;XSectionPosition=(b.MinY+b.MaxY)/2;sectionsInitialized=true;SectionChanged?.Invoke(this,(SectionAxis.X,XSectionPosition));SectionChanged?.Invoke(this,(SectionAxis.Y,YSectionPosition));}
}
