#define AppName "VCutting"
#ifndef ReleaseVersionFile
#error Approved Freeze required: pass ReleaseVersionFile generated by release/versioning.py prepare
#endif
#include ReleaseVersionFile
#define AppPublisher "VCutting"
#ifndef StageRoot
#define StageRoot "stage"
#endif

[Setup]
AppId={{72D5CE59-6E07-47D0-88C6-ADE37D3368A1}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
DefaultDirName={autopf}\VCutting
DefaultGroupName=VCutting
DisableProgramGroupPage=yes
OutputDir=output
OutputBaseFilename={#SetupBaseFilename}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\CosmicDesigner.exe
CloseApplications=yes
RestartApplications=no
SetupLogging=yes
UsePreviousAppDir=yes
UsePreviousGroup=yes
VersionInfoVersion={#AppNumericVersion}
VersionInfoProductVersion={#AppNumericVersion}
VersionInfoProductTextVersion={#AppVersion}
VersionInfoTextVersion={#AppVersion}
SetupIconFile=compiler:SetupClassicIcon.ico

[Languages]
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "바탕 화면에 VCutting 바로가기 만들기"; GroupDescription: "추가 바로가기:"; Flags: unchecked

[Files]
Source: "{#StageRoot}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\VCutting.Explorer"; Filename: "{app}\VCutting.Explorer.exe"; WorkingDir: "{app}"
Name: "{group}\VCutting.Viewer"; Filename: "{app}\VCutting.Viewer.exe"; WorkingDir: "{app}"
Name: "{group}\VCutting.Simulator"; Filename: "{app}\VCutting.Simulator.exe"; WorkingDir: "{app}"
Name: "{group}\VCutting.Drawer"; Filename: "{app}\VCutting.Drawer.exe"; WorkingDir: "{app}"
Name: "{group}\VCutting"; Filename: "{app}\CosmicDesigner.exe"; WorkingDir: "{app}"
Name: "{group}\CosmicConvert"; Filename: "{app}\CosmicConvert.exe"; WorkingDir: "{app}"
Name: "{group}\VCutting 제거"; Filename: "{uninstallexe}"
Name: "{autodesktop}\VCutting"; Filename: "{app}\CosmicDesigner.exe"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\CosmicDesigner.exe"; Description: "VCutting 실행"; Flags: nowait postinstall skipifsilent
